
package me.yv84.helloworldws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsFoo", targetNamespace = "http://helloworldws.yv84.me/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsFoo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEcho", targetNamespace = "http://helloworldws.yv84.me/", className = "me.yv84.helloworldws.GetEcho")
    @ResponseWrapper(localName = "getEchoResponse", targetNamespace = "http://helloworldws.yv84.me/", className = "me.yv84.helloworldws.GetEchoResponse")
    @Action(input = "http://helloworldws.yv84.me/wsFoo/getEchoRequest", output = "http://helloworldws.yv84.me/wsFoo/getEchoResponse")
    public String getEcho(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://helloworldws.yv84.me/", className = "me.yv84.helloworldws.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://helloworldws.yv84.me/", className = "me.yv84.helloworldws.GetListResponse")
    @Action(input = "http://helloworldws.yv84.me/wsFoo/getListRequest", output = "http://helloworldws.yv84.me/wsFoo/getListResponse")
    public List<String> getList();

}
